//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string username { get; set; }
        public string userid { get; set; }
        public string pswd { get; set; }
        public string score { get; set; }
    }
}
